apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: challenge-5a-s1
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: front
        image: gatien1/challenge-5a-s1-frontend:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: challenge-5a-s1
spec:
  type: NodePort
  selector:
    app: react
  ports:
  - protocol: TCP
    port : 8888
    targetPort: 8080
    nodePort: 30000