apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: challenge-5a-s1
spec:
  tls:
  - hosts:
    - bliblablou.day
    secretName: bliblablou-tls
  defaultBackend:
    service:
      name: frontend-service
      port:
        number: 8080
