version: '3'

services:
  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    volumes:
      - .:/srv/app
    links:
      - php
    ports:
      - '8888:80'
    depends_on:
      - database
    environment:
      XDEBUG_CONFIG: >-
        idekey=VSCODE
        remote_host=host.docker.internal
      XDEBUG_MODE: debug
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: php_dev
    volumes:
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.config/composer:/home/prod/.composer
      - .:/srv/app
    depends_on:
      - database

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025:1025", "1080:1080"]
    depends_on:
      - database
###< symfony/mailer ###

volumes:
  database_data:
