vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        company_kbis:
            uri_prefix: /company_kbis
            upload_destination: '%kernel.project_dir%/public/company_kbis'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        company_logo:
            uri_prefix: /company_logo
            upload_destination: '%kernel.project_dir%/public/company_logo'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
