vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        company_kbis:
            uri_prefix: /company_kbis
            upload_destination: '%kernel.project_dir%/public/company_kbis'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        company_logo:
            uri_prefix: /company_logo
            upload_destination: '%kernel.project_dir%/public/company_logo'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        company_picture:
            uri_prefix: /establishment_picture
            upload_destination: '%kernel.project_dir%/public/establishment_picture'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        avatar_employee:
            uri_prefix: /avatar_employee
            upload_destination: '%kernel.project_dir%/public/avatar_employee'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
