name: Deploy bakend to VPS
run-name: ${{ github.actor }} deployed backend to VPS (${{ github.sha }})

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

env:
  DOCKERHUB_REPO_BACKEND: ${{ secrets.DOCKERHUB_USERNAME }}/challenge-5a-s1-backend

jobs:
  publish_backend:
    runs-on: ubuntu-latest
    name: Publish backend image
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Copiyng .env file
        run: cp .env.prod.example .env
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "./backend"
          push: true
          tags: ${{ env.DOCKERHUB_REPO_BACKEND }}:latest, ${{ env.DOCKERHUB_REPO_BACKEND }}:${{ github.sha }}
